# Generated by Django 5.2.6 on 2026-02-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
